### ISSUE TITLE
Add jsonl download link to the swagger pages

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/landing-page#11]
neo4j is fine, but jsonl would be nicer

@dhimmel

**Comment by dhimmel** [comment]
Thanks @cbizon for posting this based on the demo feedback at the CZI/EveryCure workshop.

Both the `neo4j` and `jsonl` formats are useful. Specifically, the JSON lines interested me as a quick way to start working with the graph and as a data

I believe the format will be the [kgx as JSON lines](https://github.com/biolink/kgx/blob/24349ca4931734301bd3c45e17a6a0a27a3a42ad/specification/kgx-format.md#kgx-format-as-jsonlines), so this will actually be 2 files (one for nodes and one for edges). I'm looking forward to trying out kgx as well.

**Comment by EvanDietzMorris** [comment]
Hey @dhimmel - jsonl is the file format used throughout our KG building pipeline (https://github.com/RobokopU24/ORION), so we have every graph in that format as well. They are not necessarily strictly following the KGX format (mostly because that isn't defined very thoroughly, especially for jsonl), for example "provided_by" as an edge attribute has been replaced with biolink compliant terms. We are about to release new versions of our graphs early next week and I will make the jsonl files publicly available. Feel free to reach out to me if you want to discuss this or want jsonl files for existing versions of a graph.

**Comment by cbizon** [comment]
I think what would be great @EvanDietzMorris is if the jsonl links showed up on the robokop pages like the neo4j dump files do

**Comment by EvanDietzMorris** [comment]
New versions of our KGs have been deployed and we've updated the api-docs to include a link to the neo4j dump, the jsonl files, and a metadata file for that graph (e.g. RobokopKG.meta.json).

https://robokop.renci.org/api-docs/docs/automat/robokop-kg

**Comment by dhimmel** [comment]
Awesome and love perusing `RobokopKG.meta.json` to get some high level stats and construction details. Can likely close this issue 🚀 !

> They are not necessarily strictly following the KGX format (mostly because that isn't defined very thoroughly, especially for jsonl), for example "provided_by" as an edge attribute has been replaced with biolink compliant terms

I did want to follow up on this point, but mainly as a way to understand more about KGX. Does the KGX validator consider these files valid? Are there degrees of KGX conformity? For example, using the KGX field names for nodes and edges provides nice standardization even if say an edge type does not exist in biolink. Perhaps my question is whether KGX is accepting and suitable for data that mostly follows the KGX spec with some deviations?

**Comment by EvanDietzMorris** [comment]
This is a bit of a tricky question. The short answer is that I'm not 100% sure at this point because we don't actually use the KGX software package itself in our current pipeline. This is mainly for historical reasons and the fact that AFAIK active development for KGX is not currently funded. I'm fairly certain that KGX validation checks for some core required attributes on nodes and edges, but that they can also have any number of additional attributes. I think it checks against the biolink model where applicable, but that it generates a report of errors and doesn't actually transform or fix the errors for you. So to answer your last question, I think, mostly yes.

Just FYI - for ORION, our KG pipeline, we use KGX-like files but not the KGX package itself. We use other tools to normalize KGs. Predicates are run through a biolink lookup tool to convert them to valid biolink predicates (https://bl-lookup-sri.renci.org/docs).  Nodes are processed with the node normalizer to make sure they have proper biolink types associated with them, as well as making sure synonymous ids converge on a preferred ID (https://nodenormalization-sri.renci.org/docs). Throughout this process every output file is written with a standard KGX-like format, but that's only really enforced and validated by ORION itself. We haven't put much emphasis on strict KGX validation of these files recently because currently they are mostly only used internally. For us they get loaded into a Neo4j and then exposed with TRAPI endpoints or cypher, so the users don't typically see the KGX files.

All of that being said, I admit it's not an ideal state of things. It's becoming clear more people are interested in the KGX files themselves. It'd be great if KGX was being actively developed and maintained and more groups used it more seriously, including us. I'm going to close this issue, but am happy to discuss this more. Shoot me an email if you'd like.
